version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/ow-db
    depends_on:
      - mongo
    command: sh -c "npm run seed && npm start"  # Adicione isso para rodar o seed ao iniciar

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
